<?php
require_once __DIR__ . '/user-bootstrap.php';
$admin=vuelotel_require_admin();$db=vuelotel_db();$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='GET'){$users=$db->query("SELECT u.id,u.email,u.display_name,u.role,u.status,u.created_at,u.last_login_at,(SELECT COUNT(*) FROM alerts a WHERE a.user_id=u.id AND a.active=1 AND a.expires_at>strftime('%s','now')) active_alerts FROM users u ORDER BY u.created_at DESC")->fetchAll();$config=hotelio_config();$usagePath=dirname(hotelio_config_path()).DIRECTORY_SEPARATOR.'.hotelio-flight-data'.DIRECTORY_SEPARATOR.'usage.json';$usage=is_file($usagePath)?json_decode(file_get_contents($usagePath),true):array();$emails=$db->query("SELECT COUNT(*) total,COALESCE(SUM(success),0) sent FROM mail_log WHERE created_at>strftime('%s','now')-2592000")->fetch();$activeAlerts=(int)$db->query("SELECT COUNT(*) FROM alerts WHERE active=1 AND expires_at>strftime('%s','now')")->fetchColumn();vuelotel_json(200,array('users'=>$users,'settings'=>array('publicRegistration'=>vuelotel_setting('public_registration','1')==='1','maxAlerts'=>(int)vuelotel_setting('max_alerts_per_user','5')),'usage'=>array('flightCalls'=>(int)($usage['monthly_calls']??0),'flightLimit'=>(int)($config['flights']['monthly_limit']??120),'emailsAttempted'=>(int)$emails['total'],'emailsSent'=>(int)$emails['sent'],'activeAlerts'=>$activeAlerts)));}
if($method!=='POST')vuelotel_json(405,array('error'=>'Método no permitido.'));
$body=vuelotel_body();$action=(string)($body['action']??'');$now=time();
if($action==='settings'){$enabled=!empty($body['publicRegistration'])?'1':'0';$db->prepare('INSERT INTO app_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value')->execute(array('public_registration',$enabled));vuelotel_json(200,array('ok'=>true));}
if($action==='create'){$email=strtolower(trim((string)($body['email']??'')));$password=(string)($body['password']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10)vuelotel_json(400,array('error'=>'Correo o contraseña no válidos.'));try{$db->prepare('INSERT INTO users(email,display_name,password_hash,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)')->execute(array($email,trim((string)($body['displayName']??'')),password_hash($password,PASSWORD_DEFAULT),($body['role']??'user')==='admin'?'admin':'user','active',$now,$now));}catch(PDOException $e){vuelotel_json(409,array('error'=>'El correo ya está registrado.'));}vuelotel_json(201,array('id'=>(int)$db->lastInsertId()));}
if($action==='update'){$id=(int)($body['id']??0);if($id===(int)$admin['id']&&($body['status']??'active')!=='active')vuelotel_json(400,array('error'=>'No puedes bloquear tu propia cuenta.'));$db->prepare('UPDATE users SET display_name=?,role=?,status=?,updated_at=? WHERE id=?')->execute(array(trim((string)($body['displayName']??'')),($body['role']??'user')==='admin'?'admin':'user',($body['status']??'active')==='blocked'?'blocked':'active',$now,$id));vuelotel_json(200,array('ok'=>true));}
if($action==='delete'){$id=(int)($body['id']??0);if($id===(int)$admin['id'])vuelotel_json(400,array('error'=>'No puedes eliminar tu propia cuenta.'));$db->prepare('DELETE FROM users WHERE id=?')->execute(array($id));vuelotel_json(200,array('ok'=>true));}
vuelotel_json(400,array('error'=>'Acción no válida.'));
